language: python
sudo: required

install:
    - sudo apt install curl python3 python3-setuptools python3-numpy python3-requests poppler-utils
    - git clone https://github.com/JBBgameich/pdf-table-extract
    - cd pdf-table-extract
    - sudo mkdir -p /usr/lib/python3.4/site-packages/
    - sudo python3 setup.py install
    - cd ..

script:
    - python3 update.py $USERNAME $PASSWORD
